version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: indisumai-nginx-ssl
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt:ro
    networks:
      - indisumai-network

  certbot:
    image: certbot/certbot:latest
    container_name: indisumai-certbot-ssl
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email contact@indisumai.com --agree-tos --no-eff-email -d indisumai.com -d www.indisumai.com

volumes:
  certbot-etc:
  certbot-var:

networks:
  indisumai-network:
    driver: bridge
