services:
  nginx:
    image: nginx:alpine
    container_name: indisumai-final
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - certbot-certs:/etc/letsencrypt:ro
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - indisumai-network

volumes:
  certbot-certs:
    external: true

networks:
  indisumai-network:
    driver: bridge
