version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: indisumai-nginx-http
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - indisumai-network

networks:
  indisumai-network:
    driver: bridge
